name: Gradle test, publish and javadoc

on:
  push:
    branches: [main]

jobs:
  test:
    uses: GufliMC/scripts/.github/workflows/java-gradle-test.yml@main

  publish:
    needs: test
    uses: GufliMC/scripts/.github/workflows/java-gradle-publish.yml@main
    secrets:
      JORISG_REPO_USERNAME: ${{ secrets.JORISG_REPO_USERNAME }}
      JORISG_REPO_PASSWORD: ${{ secrets.JORISG_REPO_PASSWORD }}

  javadoc:
    needs: test
    uses: GufliMC/scripts/.github/workflows/java-gradle-javadoc.yml@main